name: Property Release Automation - External Repo

on:
  workflow_dispatch:
    inputs:
      BASE_PATH:
        description: "Base path for the release folder"
        required: true
        type: string

env:
  TARGET_REPO: "Skrishna23/NaaP"  # Change to your actual repo
  PROPERTIES_BRANCH: "dev-properties"           # Branch where property files are stored
  RELEASE_BRANCH: "releasemanagement" # The correct branch in the target repo

jobs:
  update_properties:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          ref: ${{ env.PROPERTIES_BRANCH }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch and Checkout Release Folder from Target Repo
        run: |
          BASE_PATH="${{ github.event.inputs.BASE_PATH }}"
          RELEASE_BRANCH="${{ env.RELEASE_BRANCH }}"

          echo "Fetching release branch: $RELEASE_BRANCH from ${{ env.TARGET_REPO }}"
          git fetch origin "$RELEASE_BRANCH" || { echo "::error::Branch $RELEASE_BRANCH not found!"; exit 1; }

          echo "Checking out release folder from branch: $RELEASE_BRANCH"
          git checkout origin/"$RELEASE_BRANCH" -- "$BASE_PATH" || { echo "::error::Release folder not found in $RELEASE_BRANCH!"; exit 1; }

          [ -d "$BASE_PATH" ] || { echo "::error::[ERROR] Release folder does not exist: $BASE_PATH"; exit 1; }

      - name: Process Property File Changes
        run: |
          BASE_PATH="${{ github.event.inputs.BASE_PATH }}"
          FULL_PATH="$GITHUB_WORKSPACE/$BASE_PATH"
          LOG_FILE="property_changes.log"

          echo "Processing property file changes..." > "$LOG_FILE"

          find "$FULL_PATH" -type f -name "*.properties" | while read -r FILE_PATH; do
            FILE_NAME=$(basename "$FILE_PATH")

            [ -f "$FILE_NAME" ] || { echo "::error::Property file '$FILE_NAME' not found!"; exit 1; }

            TEMP_FILE="${FILE_NAME}.tmp"
            cp "$FILE_NAME" "$TEMP_FILE"

            SECTION=""
            while IFS= read -r line; do
              [[ -z "$line" || "$line" =~ ^# ]] && continue

              case "$line" in
                "[ADD]") SECTION="ADD"; continue ;;
                "[UPDATE]") SECTION="UPDATE"; continue ;;
                "[REMOVE]") SECTION="REMOVE"; continue ;;
              esac

              KEY=$(echo "$line" | cut -d= -f1)
              VALUE=$(echo "$line" | cut -d= -f2-)

              case "$SECTION" in
                "ADD")
                  grep -q "^$KEY=" "$TEMP_FILE" && { echo "::error::Key '$KEY' already exists!"; exit 1; }
                  echo "$line" >> "$TEMP_FILE"
                  ;;
                "UPDATE")
                  grep -q "^$KEY=" "$TEMP_FILE" || { echo "::error::Key '$KEY' not found!"; exit 1; }
                  sed -i "s|^$KEY=.*|$KEY=$VALUE|" "$TEMP_FILE"
                  ;;
                "REMOVE")
                  grep -q "^$KEY=" "$TEMP_FILE" || { echo "::error::Key '$KEY' not found!"; exit 1; }
                  sed -i "/^$KEY=/d" "$TEMP_FILE"
                  ;;
              esac
            done < "$FILE_PATH"

            mv "$TEMP_FILE" "$FILE_NAME"
          done

      - name: Display Logs
        run: cat property_changes.log

      - name: Remove Release Folder Before Commit
        run: |
          BASE_PATH="${{ github.event.inputs.BASE_PATH }}"
          [ -d "$BASE_PATH" ] && git rm -rf --cached "$BASE_PATH" || echo "Folder not tracked, skipping removal"
          rm -rf "$BASE_PATH"

      - name: Commit and Push Changes to Target Repo
        run: |
          git add -u
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi
          git commit -m "Updated properties from release folder: ${{ github.event.inputs.BASE_PATH }}"
          git push origin "${{ env.PROPERTIES_BRANCH }}" || { echo "::error::Push failed!"; exit 1; }
