name: Property Release Automation - NaaP

on:
  workflow_dispatch:
    inputs:
      BASE_PATH:
        description: "Base path for the release folder in releasemanagement branch"
        required: true
        type: string

jobs:
  update_properties:
    runs-on: ubuntu-latest
    env:
      GITOPS_REPO: "Skrishna23/Project_NaaP"  # 🔹 Replace with actual repo
      RELEASE_BRANCH: "releasemanagement"
      PROPERTIES_BRANCH: "dev-properties"

    steps:
      - name: Checkout CICD Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone GitOps Repository
        run: |
          set -e
          echo "Cloning GitOps repository '${{ env.GITOPS_REPO }}'..."
          git clone --depth 1 https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ env.GITOPS_REPO }}.git gitops-repo
          cd gitops-repo

          echo "DEBUG: Listing all remote branches..."
          git ls-remote --heads origin

      - name: Fetch & Checkout Release Folder from releasemanagement Branch
        run: |
          set -e
          cd gitops-repo

          echo "DEBUG: BASE_PATH='${{ github.event.inputs.BASE_PATH }}'"
          echo "DEBUG: RELEASE_BRANCH='${{ env.RELEASE_BRANCH }}'"

          # Fetch all branches
          git fetch --all

          # List all remote branches to debug
          echo "DEBUG: Available branches:"
          git branch -r

          # Check if the release branch exists remotely
          if git branch -r | grep -q "origin/${{ env.RELEASE_BRANCH }}"; then
            echo "::notice::[SUCCESS] Found remote branch '${{ env.RELEASE_BRANCH }}'. Checking out..."
            git checkout "${{ env.RELEASE_BRANCH }}"
            git pull origin "${{ env.RELEASE_BRANCH }}"
          else
            echo "::error::[ERROR] Release branch '${{ env.RELEASE_BRANCH }}' does not exist in remote repository!"
            exit 1
          fi

          # Verify if the release folder exists
          if [ ! -d "${{ github.event.inputs.BASE_PATH }}" ]; then
            echo "::error::[ERROR] Release folder '${{ github.event.inputs.BASE_PATH }}' does not exist!"
            exit 1
          fi

          echo "::notice::[SUCCESS] Checked out release folder from '${{ env.RELEASE_BRANCH }}'."


      - name: Fetch & Checkout Properties Folder from dev-properties Branch
        run: |
          set -e
          cd gitops-repo

          git fetch origin "${{ env.PROPERTIES_BRANCH }}"

          if git branch -r | grep -q "origin/${{ env.PROPERTIES_BRANCH }}"; then
            git checkout -b "${{ env.PROPERTIES_BRANCH }}" "origin/${{ env.PROPERTIES_BRANCH }}"
          else
            echo "::error::[ERROR] Properties branch '${{ env.PROPERTIES_BRANCH }}' does not exist!"
            exit 1
          fi

          echo "::notice::[SUCCESS] Checked out properties folder from '${{ env.PROPERTIES_BRANCH }}'."

      - name: Process Property File Changes
        run: |
          set -e
          RELEASE_PATH="gitops-repo/${{ github.event.inputs.BASE_PATH }}"
          PROPERTIES_PATH="gitops-repo"
          LOG_FILE="property_changes.log"

          echo "Processing changes from $RELEASE_PATH..." > $LOG_FILE

          for FILE_PATH in $(find "$RELEASE_PATH" -type f ! -name "*.*"); do
            FILE_NAME=$(basename "$FILE_PATH")
            PROPERTY_FILE="$PROPERTIES_PATH/$FILE_NAME.properties"

            if [ ! -f "$PROPERTY_FILE" ]; then
              echo "::error::[ERROR] Matching property file '$PROPERTY_FILE' not found. Workflow failed!" | tee -a $LOG_FILE
              exit 1
            fi

            echo "[INFO] Applying changes from $FILE_PATH to $PROPERTY_FILE" >> $LOG_FILE

            TEMP_FILE="${PROPERTY_FILE}.tmp"
            cp "$PROPERTY_FILE" "$TEMP_FILE"

            SECTION=""
            while IFS= read -r line; do
              [[ -z "$line" || "$line" =~ ^# ]] && continue

              case "$line" in
                "[ADD]") SECTION="ADD"; continue ;;
                "[UPDATE]") SECTION="UPDATE"; continue ;;
                "[REMOVE]") SECTION="REMOVE"; continue ;;
              esac

              if [[ "$SECTION" == "ADD" ]]; then
                KEY=$(echo "$line" | cut -d= -f1)

                if grep -q "^$KEY=" "$TEMP_FILE"; then
                  echo "::error::[ERROR] Key '$KEY' already exists in $PROPERTY_FILE. Workflow failed!" | tee -a $LOG_FILE
                  exit 1
                fi

                echo "$line" >> "$TEMP_FILE"
                echo "[ADD] Added: $line in $PROPERTY_FILE" >> $LOG_FILE

              elif [[ "$SECTION" == "UPDATE" ]]; then
                KEY=$(echo "$line" | cut -d= -f1)
                VALUE=$(echo "$line" | cut -d= -f2-)

                if ! grep -q "^$KEY=" "$TEMP_FILE"; then
                  echo "::error::[ERROR] Key '$KEY' not found in $PROPERTY_FILE for update. Workflow failed!" | tee -a $LOG_FILE
                  exit 1
                fi

                OLD_VALUE=$(grep "^$KEY=" "$TEMP_FILE" | cut -d= -f2-)

                if [[ "$OLD_VALUE" == "$VALUE" ]]; then
                  echo "::error::[ERROR] Key '$KEY' in $PROPERTY_FILE already has the same value. No change detected. Workflow failed!" | tee -a $LOG_FILE
                  exit 1
                fi

                sed -i "s|^$KEY=.*|$KEY=$VALUE|" "$TEMP_FILE"
                echo "[UPDATE] Updated: $KEY=$VALUE in $PROPERTY_FILE" >> $LOG_FILE

              elif [[ "$SECTION" == "REMOVE" ]]; then
                KEY=$(echo "$line" | cut -d= -f1)

                if ! grep -q "^$KEY=" "$TEMP_FILE"; then
                  echo "::error::[ERROR] Key '$KEY' not found in $PROPERTY_FILE for removal. Workflow failed!" | tee -a $LOG_FILE
                  exit 1
                fi

                sed -i "/^$KEY=/d" "$TEMP_FILE"
                echo "[DELETE] Removed: $KEY from $PROPERTY_FILE" >> $LOG_FILE
              fi
            done < "$FILE_PATH"

            mv "$TEMP_FILE" "$PROPERTY_FILE"
          done

      - name: Commit and Push Changes to dev-properties Branch
        run: |
          cd gitops-repo
          git add -u

          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Updated properties from release: ${{ github.event.inputs.BASE_PATH }}"
            git push origin "${{ env.PROPERTIES_BRANCH }}"
          fi
